#global_costmap
global_frame: map
robot_base_frame: base_link
update_frequency: 3
publish_frequency: 3
always_send_full_costmap: false
plugins:
   
   - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
